// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	model "github.com/go-web/pkg/model/event"
	mock "github.com/stretchr/testify/mock"
)

// EventRepository is an autogenerated mock type for the EventRepository type
type EventRepository struct {
	mock.Mock
}

// CreateEvent provides a mock function with given fields: _a0
func (_m *EventRepository) CreateEvent(_a0 *model.Event) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Event) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetEventsByGroupId provides a mock function with given fields: groupId
func (_m *EventRepository) GetEventsByGroupId(groupId string) ([]*model.Event, error) {
	ret := _m.Called(groupId)

	var r0 []*model.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*model.Event, error)); ok {
		return rf(groupId)
	}
	if rf, ok := ret.Get(0).(func(string) []*model.Event); ok {
		r0 = rf(groupId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(groupId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEventRepository creates a new instance of EventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventRepository {
	mock := &EventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
