// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	event "github.com/go-web/pkg/model/event"
	mock "github.com/stretchr/testify/mock"

	model "github.com/go-web/pkg/model/member"
)

// EventMemberService is an autogenerated mock type for the EventMemberService type
type EventMemberService struct {
	mock.Mock
}

// CountMembersByEventId provides a mock function with given fields: ids
func (_m *EventMemberService) CountMembersByEventId(ids []string) ([]*model.CountMembersByEventId, error) {
	ret := _m.Called(ids)

	var r0 []*model.CountMembersByEventId
	var r1 error
	if rf, ok := ret.Get(0).(func([]string) ([]*model.CountMembersByEventId, error)); ok {
		return rf(ids)
	}
	if rf, ok := ret.Get(0).(func([]string) []*model.CountMembersByEventId); ok {
		r0 = rf(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.CountMembersByEventId)
		}
	}

	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateEventMember provides a mock function with given fields: eventRequest
func (_m *EventMemberService) CreateEventMember(eventRequest *event.AddMemberToEventRequest) (*event.AddMemberToEventResponse, error) {
	ret := _m.Called(eventRequest)

	var r0 *event.AddMemberToEventResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*event.AddMemberToEventRequest) (*event.AddMemberToEventResponse, error)); ok {
		return rf(eventRequest)
	}
	if rf, ok := ret.Get(0).(func(*event.AddMemberToEventRequest) *event.AddMemberToEventResponse); ok {
		r0 = rf(eventRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*event.AddMemberToEventResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*event.AddMemberToEventRequest) error); ok {
		r1 = rf(eventRequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventMembers provides a mock function with given fields: request
func (_m *EventMemberService) GetEventMembers(request *model.GetEventMembersRequest) (*model.GetEventMembersResponse, error) {
	ret := _m.Called(request)

	var r0 *model.GetEventMembersResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.GetEventMembersRequest) (*model.GetEventMembersResponse, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(*model.GetEventMembersRequest) *model.GetEventMembersResponse); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.GetEventMembersResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.GetEventMembersRequest) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEventMemberService creates a new instance of EventMemberService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventMemberService(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventMemberService {
	mock := &EventMemberService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
