// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	model "github.com/go-web/pkg/model/venue"
	mock "github.com/stretchr/testify/mock"

	pkgmodel "github.com/go-web/pkg/model"
)

// VenueService is an autogenerated mock type for the VenueService type
type VenueService struct {
	mock.Mock
}

// CreateVenue provides a mock function with given fields: venueRequest
func (_m *VenueService) CreateVenue(venueRequest *model.Venue) (*model.Venue, error) {
	ret := _m.Called(venueRequest)

	var r0 *model.Venue
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.Venue) (*model.Venue, error)); ok {
		return rf(venueRequest)
	}
	if rf, ok := ret.Get(0).(func(*model.Venue) *model.Venue); ok {
		r0 = rf(venueRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Venue)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.Venue) error); ok {
		r1 = rf(venueRequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVenues provides a mock function with given fields: request
func (_m *VenueService) GetVenues(request *pkgmodel.Filter) (*model.GetVenueResponse, error) {
	ret := _m.Called(request)

	var r0 *model.GetVenueResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*pkgmodel.Filter) (*model.GetVenueResponse, error)); ok {
		return rf(request)
	}
	if rf, ok := ret.Get(0).(func(*pkgmodel.Filter) *model.GetVenueResponse); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.GetVenueResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*pkgmodel.Filter) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVenueService creates a new instance of VenueService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVenueService(t interface {
	mock.TestingT
	Cleanup(func())
}) *VenueService {
	mock := &VenueService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
